### ISSUE TITLE
Poseidon pod stuck in "Init:0/1"

### ISSUE THREAD

**Issue by islinwb** [kubernetes-sigs/poseidon#125]
I followed guide in https://github.com/kubernetes-sigs/poseidon/blob/master/docs/install/README.md and tried it in two VMs. The poseidon pod stuck in "Init:0/1" in one of the VMs.

`docker logs <init-firmamentservice_contianer_ID>`:
```
waiting for firmamentservice
nslookup: can't resolve 'firmament-service.kube-system'
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local
```
`docker exec -it <init-firmamentservice_contianer_ID> sh`
```
[ root@poseidon-6d45696849-gxtpg:/ ]$ nslookup firmament-service.kube-system
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'firmament-service.kube-system'
[ root@poseidon-6d45696849-gxtpg:/ ]$ cat /etc/resolv.conf
nameserver 10.0.0.10
search kube-system.svc.cluster.local svc.cluster.local cluster.local huawei.com
options ndots:5
[ root@poseidon-6d45696849-gxtpg:/ ]$ nslookup firmament-service.kube-system.svc.cluster.local
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      firmament-service.kube-system.svc.cluster.local
Address 1: 10.0.0.160 firmament-service.kube-system.svc.cluster.local
```
After changing `firmament-service.kube-system` to `firmament-service.kube-system.svc.cluster.local` in https://raw.githubusercontent.com/kubernetes-sigs/poseidon/master/deploy/poseidon-deployment.yaml, it works.
```
initContainers:
      - name: init-firmamentservice
        image: radial/busyboxplus:curl
        command: ['sh', '-c', 'until nslookup firmament-service.kube-system; do echo waiting for firmamentservice; sleep 1; done;']
```
